### ISSUE TITLE
Issue with symfony

### ISSUE THREAD

**Issue by wturnerharris** [pantheon-systems/wordpress-composer-managed#75] opened 2023-03-21 22:12 UTC
**Issue:**
When fresh installing, getting a critical error.
<img width="840" alt="Screenshot 2023-03-21 at 6 06 14 PM" src="https://user-images.githubusercontent.com/887488/226752391-c5d0655a-1a03-4455-81d6-432872671c5d.png">
<img width="492" alt="Screenshot 2023-03-21 at 6 06 27 PM" src="https://user-images.githubusercontent.com/887488/226752714-9a967086-9d64-4cf2-ace2-13fe60f7f528.png">

**Resolution:**
Looks like one of the dependencies has an issue with PHP8. Rolling back the dependency to 6.0.x for Finder on the theme level composer fixes this:
```
    "symfony/finder": "6.0.*",
```
Similar issue [here](https://stackoverflow.com/questions/72436803/laravel-9-composer-syntax-error-unexpected-token)

**Comment by jazzsequence** [comment] 2023-03-22 14:48
@wturnerharris 
`symfony/finder` is not a required package in the [main composer file](https://github.com/pantheon-systems/wordpress-composer-managed/blob/default/composer.json#L52-L68). It's not even required in [Sage](https://github.com/roots/sage/blob/main/composer.json#L41-L43) -- which, to be clear, isn't something that we support, it's just something we have an installer for. If you need support for Sage, I'd recommend requesting it in the [Roots/Sage repository](https://github.com/roots/sage/).

I ran a `composer update` on an environment that uses this upstream and Sage and could not reproduce this issue. Can you provide more details about what triggers this error?

**Comment by wturnerharris** [comment] 2023-03-22 23:43
That is very strange. I ran the installer like five different times and every time ran into that crash after enabling the sage starter.

**Comment by wturnerharris** [comment] 2023-03-23 02:36
Here's a [loom video](https://www.loom.com/share/055695e110ab4dfca2b7425f39c9e66a) that you can watch on 2x.

1. Created a new site using this upstream
2. Installed sage using sage install script

**Comment by wturnerharris** [comment] 2023-03-27 21:22
@jazzsequence - glad the loom helped see the full scope. 

In terms of the workflow/timing conundrum, I did do a couple of things not in this loom in prior test installs that didn't help in either case:
- First I increased the wait time in the script from 30s to 500s. I thought that was a generous amount of time to clear the workflow. In fact it did complete after some time, but nothing was ever committed and the error still occurred for me. 
- Second, I manually switched to sftp mode and then activated the theme, but no files were committed and the error still occurred. 

Re: acorn, per the sage Github: "Harness the power of [Laravel](https://laravel.com/) and its available packages thanks to [Acorn](https://github.com/roots/acorn)"

Noting that I think this might be an issue with expected file/symlink mapping. I had this issue with lando on local and saw errors reported on Acorn file path. Xdebug was helpful in tracking down a series of "this folder must be writable" messages and finally got a good permission/symlink setup with Shared files for lando, but this never "worked" for me on the Pantheon side. I'll do one last install. I'll also review `dev-main` and see if that helps too.

**Comment by jazzsequence** [comment] 2023-03-27 21:27
@wturnerharris If you can, try the script as it's been updated in https://github.com/pantheon-systems/wordpress-composer-managed/pull/82/files -- there's some error handling in there that might at least trigger an exit in the right places if it can't do a thing.

**Comment by jazzsequence** [comment] 2023-09-21 20:55
As this has not been updated in a while (and may have been addressed in #82 or subsequent updates), closing this issue for now. I'm planning on coming back to the script and add some behavioral testing to ensure the script runs as expected, so we may come back to this at some point, but feel free to re-open if this is still an issue.

**Closed by jazzsequence** 2023-09-21 20:55 UTC
