### ISSUE TITLE
`wp db create` fails

### ISSUE THREAD

**Issue by codepuncher** [pantheon-systems/wordpress-composer-managed#25] opened 2022-09-20 22:52 UTC
Usually when using Bedrock, I would populate my `.env` file using https://github.com/roots/trellis-cli.
I have done the same using this Pantheon repo but renamed to `.env.local`.

I then run `wp db create` from the bedrock directory to create my local database.

Unfortunately whatever changes that have been made to this repo has resulted in local `.env` not working at all.

I'd take a guess at something here may be related https://github.com/pantheon-systems/wordpress-composer-managed/commit/bc11ddbd6529f7bb455587af07a1cfea2b9cfd5d

Separetely, because `Config::define('WP_HOME', env('WP_HOME')` was moved **after** `Config::define('WP_HOME', env('WP_HOME')` I was also getting a fatal error.

**Comment by jspellman814** [comment] 2022-09-21 14:31
Thank you for this report @codepuncher! Are you able to share the error message(s) you receive when running `wp db create`.

We are working on some separate changes for local development that _might_ address this issue. In the case that it doesn't, we'll open a bug ticket and will be sure to look into this.

**Comment by rwagner00** [comment] 2022-09-22 15:22
A ticket has been opened to take care of this, thanks again for the report!

**Comment by backlineint** [comment] 2022-10-12 19:54
We've run into this as well with our dev sandbox for Decoupled WordPress sites. Specifically using Lando.

Poking at this a bit I've found that based on what @codepuncher pointed out, if i restore the lines here: https://github.com/pantheon-systems/wordpress-composer-managed/commit/bc11ddbd6529f7bb455587af07a1cfea2b9cfd5d#diff-53ea5a45a4b413ca49c7fac3f022e1dcbc2c203dcab4a1e7a34d1a8d65b26977L51-L56

`lando wp` commands start working again, but the actual WordPress site becomes unstable (I think I starter to see 404s) until those lines are removed again.

**Comment by jspellman814** [comment] 2022-11-22 21:17
👋 @codepuncher I haven't been unable to reproduce this issue, and believe the changes introduced in #29 were the resolution for this. Would you be able to pull the latest code from the [upstream](https://github.com/pantheon-upstreams/wordpress-composer-managed) and confirm that you're no longer seeing this issue? Thank you!

**Comment by scottbuscemi** [comment] 2022-11-23 16:36
Closing as resolved, but feel free to re-open if you're still experiencing this!

**Closed by scottbuscemi** 2022-11-23 16:36 UTC
