### ISSUE TITLE
Any known issues with blade directives on Pantheon

### ISSUE THREAD

**Issue by wturnerharris** [pantheon-systems/wordpress-composer-managed#77] opened 2023-03-23 02:59 UTC
Issue:
- Using the [sage-svg](https://github.com/Log1x/sage-svg) package for inline svgs
- This opens a `@svg` directive for blade templates
- This works locally
- This does not work on Pantheon

Request:
- Are there any known issues with blade directives?
- Where is a good place to narrow down the issue?

Not encountering any errors, but the directive simply outputs the same as a plaintext string.

<img width="946" alt="Screenshot 2023-03-22 at 11 06 23 PM" src="https://user-images.githubusercontent.com/887488/227091377-312ce4eb-82f5-4046-888d-ec90fa60f671.png">

Found [this](https://discourse.roots.io/t/sage-10-on-pantheon-a-guide-and-method/19978/5) already in the wild, but nothing commented there actually worked.

**Comment by wturnerharris** [comment] 2023-03-27 15:49
@jazzsequence - it supports both uploaded files as well as assets already loaded in the theme. In either context, they work locally on lando but not on DEV (sftp or git mode) unless we use the `<?php echo get_svg()` method.

**Comment by jazzsequence** [comment] 2023-03-27 20:56
I can open an internal ticket to test this. My initial reaction is that this is not going to be explicitly supported just because we can't go down every Roots-adjacent rabbit hole, but I want to make sure I understand _why_ it's not working and whether there's a viable workaround.

**Comment by jazzsequence** [comment] 2023-03-27 21:04
I'm going to leave this open to come back to. Tracking internally as BUGS-6054 but it's marked as a low priority.

**Comment by cleverington** [comment] 2023-03-30 01:58
As a follow-up and tag-along here, I was going to recommend an extra instructions and linking to how/where to install Sage.

The "Install Script" got working and going on Lando fine, but part of the "Build" step for Sage appears to rely heavily on `yarn build` (or `npm build`), which means that there are actually a **few** directories that either need to be SymLinked or have the `.gitignore` removed and committed directly to the repository. (The theme expects both the `themes/THEME_NAME/storage` and `themes/THEME_NAME/public` folders to be writable, if I'm learning this correctly.)

I'm exploring the link Wes shared above as well, but I think ultimately that two different changes might be needed:
1. Update the script slightly to remove variously generated `.gitignore` files.
2. Add notes that `yarn build` kind of changes are required.

I'm not certain the Sage theme _itself_ may be viable as part of Composer workflow for that reason, but I can definitely still see the viability on Pantheon once the "right" combination of sym-linked folders vs hard-coded folders vs hard-coded etc. is in place.

Will chase more next time I have a minute.

**Comment by jazzsequence** [comment] 2023-03-31 15:23
@cleverington 
The goal of the install script wasn't necessarily to have a fully fleshed out workspace for Sage so much as it was to pave a path to get started that could then be used and modified by teams, etc. However, I'm happy to add to the documentation (or, ideally, link to existing documentation) if there are additional steps needed, but I don't want to get too in the weeds with it. The Composer Managed upstream _happens_ to use Bedrock as a base (although it's technically a fork), and along with Bedrock comes a lot of assumptions of compatibility for other Roots-related projects that, while we might like and strive to, Pantheon may not fully support, and we're certainly not in a position right now to fully support the entire Roots ecosystem because we have an EA Composer-based WP upstream that uses Bedrock. We debated supporting Sage at all, but we were getting some requests for it and, when we looked at it, it seemed like it needed a paved path to get started in a way that worked on our infrastructure and that it wouldn't be too hard to add that paved path.

I think that, if there are additional steps needed to fully set up a Sage theme, it would be worth opening a new issue for those so we can review that and determine what the best next steps are (e.g. expand the install script or add to the documentation). This issue appears (to me, without reproducing) to be distinct from what you're talking about.

Also, and I'm rambling now, but it's worth noting that we haven't (yet) updated our documentation on what a Build Tools-based environment looks like with the WP Composer Managed upstream. It's on the books, we plan to do that, and, in so doing, we'll obviously need to test some of this stuff, but that's where a build step like NPM or Yarn or whatever might come in, separate from the Composer/PHP side of things.

**Comment by cleverington** [comment] 2023-03-31 21:48
@wturnerharris 

As a return-to-the-original topic, I was poking a bit today and pushed up my changes.  I also sym-linked and dropped the `storage/` folder into the `uploads/` folder and SFTP-pushed it after initial `acorn` commands and the SVGs are loading.

So I think that's probably the direction we both should explore? Maybe? 

eg:
```bash
uploads:
  cache --> ../cache/
  storage --> ../themes/THEME_NAME/storage
```

**Comment by jazzsequence** [comment] 2023-10-11 18:03
Alright folks. I'm gonna close this out. We have ticket that we're tracking internally for this. I'm about to make this repository private in favor of the public upstream repository https://github.com/pantheon-upstreams/wordpress-composer-managed. If it's important, a new ticket can be opened over there (I just turned on [issues](https://github.com/pantheon-upstreams/wordpress-composer-managed)).

**Closed by jazzsequence** 2023-10-11 18:03 UTC
